# .streamlit/secrets.toml

SUPABASE_URL = "https://aybfpatjyhgvhgmlejqd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5YmZwYXRqeWhndmhnbWxlanFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODEwMzIsImV4cCI6MjA2ODg1NzAzMn0.zGSDQlPiQ2KxTFDKptm1ByP7d9zbbjUeBbUlhH4GfUA"